install.packages('rvest')
install.packages('networkD3')
install.packages('qdapRegex')
install.packages('tidygraph')
install.packages('jsonlite')
install.packages('rworldmap')
install.packages('tidytext')